### ISSUE TITLE
Create GUI to allow users to subscribe

### ISSUE THREAD

**Issue by kofiachie** [thailore/certiorem#1]

**Comment by kofiachie** [comment]
..

**Comment by thailore** [comment]
Entails:
- Setup Web Page
- Get basic GUI with Form and Drop down menu
- Capture info in form (angular double binding) 
- Send info to DB

**Comment by kofiachie** [comment]
GUI done. waiting on review and merge

**Comment by kofiachie** [comment]
Closing. Done
